ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM nusaledger_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE USAGE, SELECT ON SEQUENCES FROM nusaledger_app;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM nusaledger_app;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM nusaledger_app;
REVOKE USAGE ON SCHEMA public FROM nusaledger_app;

DO $$
BEGIN
    EXECUTE format('REVOKE CONNECT ON DATABASE %I FROM nusaledger_app', current_database());
END$$;

DROP ROLE IF EXISTS nusaledger_app;
